services:
  dashboard:
    build:
      context: ./
    container_name: "${COMPOSE_PROJECT_NAME}_dashboard"
    hostname: "${COMPOSE_PROJECT_NAME}_dashboard"
    restart: always
    ports:
      - "5000:80"
    networks:
      - network
    volumes:
      - ./data:/home/data      
  
networks:
  network:
    driver: bridge
